fluttercommunity/flutter_launcher_icons

.gitignore, bin/main.dart, lib/android.dart, lib/ios.dart
Also updated .gitignore to not include .idea/ which is auto generated by IntelliJ
=> IOS launcher icons now being auto created.

lib/ios.dart
When specifying a new icon by setting the ios: config to a new icon name, the resulting assets file in XCode was showing 2 undefined icons and a missing AppStore icon. The App Store would also throw a warning upon file upload.
This change correctly assigns the app store icon and the icon assets file no longer has any superfluous entries.
Thanks for an awesome package!
=> Correct AppStore Icon Settings

lib/android.dart, test/android_test.dart
This solves a problem that is (to us) really annoying: the code that updates the manifest always added a newline every single time. And because we ran it more often, this lead to multiple newlines added to our manifest, which then got committed to our codebase.
I fixed it - and as a bonus, I added 2 unit tests to check if we actually get the manifest transformation right 🎉  :-)
=> Fix #151 do not add extra newlines in manifest

lib/android.dart, test/android_test.dart
The code still had a bug (which I didn't cover in the tests), so a newline at the end of the file would always get removed. What I didn't know: `file.readAsLinesSync()` gets rid of the last empty newline, so we can't know if that was there or not.
Bonus: I added a new `withTempFile` method, that creates a temporary file during the tests and deletes that afterwards - really helpful for testing the full IO-roundtrip to AndroidManifest.xml files. All manifest tests now use that method and test the full thing.
=> Fix: code was always getting rid of trailing \n

pubspec.yaml
This will allow fluture `args` versions which are compatible to `2.0.0`
=> Allow compatible args dependency

lib/android.dart, lib/constants.dart, lib/main.dart
**Duplicate issues**
- closes #308 
- closes #316 
- closes #321 
- closes #324
- closes #333
- closes #339
- closes #344
- closes #349
- closes #351
- closes #356
- closes #359 
- closes #360
**Duplicate PR's**
- closes #313
- closes #319
- closes #340
- closes #353
- closes #355
=> Fix/flutter v2.8.0 support 321

CHANGELOG.md, README.md, analysis_options.yaml, bin/main.dart, lib/src/version.dart, pubspec.yaml
Thanks to build_version and build_runner the version number is automatically generated after running build_runner and should _hopefully_ be easier to update.
Also removed What's New section from README as this is pretty much duplicating what is shown in CHANGELOG file.
Closes: #350
=> fix: Incorrect version number shown

lib/android.dart
Running the flutter_launcher_icons script was failing because I had a commented line in my `build.gradle` file:
```
defaultConfig {
// minSdkVersion flutter.minSdkVersion
minSdkVersion 19
}
```
This small patch will already fix that issue.
Another issue is going to be the fact that `flutter.minSdkVersion` won't be resolved correctly. I already commented it out because that was giving me issues for something else (I think codemagic.io setup, but I'm not sure anymore). However, for now this will do and I don't really feel up to the task yet to tackle the "properties replacement" issue. Still, I might turn that into a feature request later on.
=> fix: ignore commented minSdkVersion

.github/workflows/cd-pub-deploy-published-release.yml
Resolves #369 
Also added  GitHub secrets for `PUB_ACCESS_TOKEN` and `PUB_REFRESH_TOKEN`
=> setting up automatic deployment of newly published github release

.github/workflows/ci-open-pr.yml
**Note**
This needs to be tested to confirm it is working as expected after merged - this can be done from the Actions tab
=> added workflow for auto running tests and analyzer for newly opened prs to merge into master

lib/ios.dart
the 50x50 icons are actually meant for ipad, but in our ios.dart they are marked as iphone. while the 57x57 should be 1x and 2x, while in our ios.dart we're using 1x and 3x.
This PR solves the generation of contents.json in case the specified ios config is string.
e.g.
```
flutter_icons:
ios: "AppIcon"
```
=> fix the icons 50 and 57 in contents.json

.pubignore
this handles part of https://github.com/fluttercommunity/flutter_launcher_icons/issues/379
- `pubspec.yaml` needed for PUBlishing.
- `LICENSE` due to license agreement.
- `analysis_options.yaml` for pub.dev to perform code analyze.
- `.gitignore` & `.github` because they are not present in files from pub.dev.
- `/example/*`
- `/README.md`
This is a little open to discussion, but as also as easy to change.
=> add .pubignore

lib/ios.dart
Fix for #462.
After the dependency upgrade from image 3.x.x to image 4.0.x the remove alpha for iOS no longer works and builds are rejected from the App Store.
The fix is from the example here: https://github.com/brendan-duncan/image/issues/447#issuecomment-1374543054.
All tests are passing.
=> Fix remove alpha for iOS

lib/custom_exceptions.dart, lib/ios.dart, lib/main.dart, test/macos/macos_icon_generator_test.dart
Complying with dart code formatting.
Increases score on pub.dev site.
=> style: formatted code with `dart format .`

bin/generate.dart
Binary command to generate config file template.
Command:
```sh
flutter pub run flutter_launcher_icons:generate
```
Checks the tasks `Generate flutter_launcher_icons.yaml config file with flutter pub run flutter_launcher_icons generate` in roadmap #379
=> feat: command to generate config file template

README.md, example/default_example/pubspec.yaml, lib/android.dart, lib/config/config.dart, lib/config/config.g.dart
I requested a PR for those who find it bothersome to change it manually every time. The default value for the inset is 16.
how to use:
~~~yaml
flutter_launcher_icons:
android: true
ios: true
remove_alpha_ios: true
image_path: "assets/app_icon/icon.png"
adaptive_icon_background: "assets/app_icon/adaptive_icon_background.png"
adaptive_icon_foreground: "assets/app_icon/adaptive_icon_foreground.png"
adaptive_icon_foreground_inset: 16  # default value is 16
~~~
before:
~~~xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
<background android:drawable="@drawable/ic_launcher_background"/>
<foreground android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
~~~
after:
~~~xml
<?xml version="1.0" encoding="utf-8"?> …
=> related to [issue #96], Suggestion for an easier way to apply foreground inset

README.md
Updated docs to use `dart run` as running `flutter pub run` gives back a deprecation warning
=> update readme to use dart run

test/main_test.dart
Fixes length checks tests failing due to newly introduced iOS sizes array in #569
=> fix: tests fails for the newly generated ios list

README.md
This PR updates and fixes the commands used to generate and manage configuration files for the flutter_launcher_icons package.
closes #580
=> Corrected run commands in the documentation

lib/ios.dart
Fixes: https://github.com/fluttercommunity/flutter_launcher_icons/issues/596
I did notice that with my auto format turned on a bunch of other lines where modified as well. I've checked in the analysis_options.yaml file and the rule was turned on, so no idea why I'm the first to re-format the code.
Anyways, I've tested this in my project that has flavors, and it worked. The Dark and Tinted icons have been generated and added correctly so much so that when viewed via xCode 16 all icons are placed correctly in their corresponding place. Which was not the case prior to this change.
=> Fixes the issue where the dark and tinted icons

analysis_options.yaml, lib/abs/icon_generator.dart, lib/android.dart, lib/ios.dart, lib/macos/macos_icon_generator.dart, lib/main.dart, lib/utils.dart, lib/web/web_icon_generator.dart, lib/windows/windows_icon_generator.dart, test/abs/icon_generator_test.mocks.dart, test/macos/macos_icon_generator_test.dart, test/utils_test.dart, test/web/web_icon_generator_test.dart, test/windows/windows_icon_generator_test.dart
This prevents existing async methods like createIconsFromConfig from returning while some async work that they spawned is still continuing in the background.
Should resolve issues like #550 and #612.
=> Standardize on async I/O and waiting for work to complete
